### ISSUE TITLE
Some error occured while initializing UI of Payment Gateway Activity

### ISSUE THREAD

**Issue by tusharbhambere** [paytm/paytm-allinonesdk-flutter#26]
Getting Issue Some error occured while initializing UI of Payment Gateway Activity

**Comment by Prakash128-lab** [comment]
@tusharbhambere , Please  drop a mail on [integration.dev@paytm.com] with issue in details.

**Comment by Yash20298** [comment]
I am facing the same issue when paytm app is not installed.
```
D/PGSDK   ( 6008): Starting the Service...
D/PGSDK   ( 6008): Service Started.
Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
D/PGSDK   ( 6008): Assist Enabled
D/PGSDK   ( 6008): Hide Header true
D/PGSDK   ( 6008): Initializing the UI of Transaction Page...
E/OplusCustomizeRestrictionManager( 6008): sInstance is null, start a new sInstance
I/WebViewFactory( 6008): Loading com.google.android.webview version 104.0.5112.69 (code 511206934)
Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (unsupported, reflection, allowed)
Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (unsupported, reflection, allowed)
 Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (unsupported, reflection, allowed)
 Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (unsupported, reflection, allowed)
Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (unsupported, reflection, allowed)
I/cr_WVCFactoryProvider( 6008): Loaded version=104.0.5112.69 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
I/cr_LibraryLoader( 6008): Successfully loaded native library
I/cr_CachingUmaRecorder( 6008): Flushed 9 samples from 9 histograms.
D/CompatibilityChangeReporter( 6008): Compat change id reported: 171228096; UID 10022; state: ENABLED
D/PGSDK   ( 6008): Some exception occurred while initializing UI.
W/System.err( 6008): android.util.AndroidRuntimeException: requestFeature() must be called before adding content
W/System.err( 6008): 	at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:415)
W/System.err( 6008): 	at android.app.Activity.requestWindowFeature(Activity.java:5154)
W/System.err( 6008): 	at com.paytm.pgsdk.PaytmPGActivity.initUI(PaytmPGActivity.java:198)
W/System.err( 6008): 	at com.paytm.pgsdk.PaytmPGActivity.onCreate(PaytmPGActivity.java:95)
W/System.err( 6008): 	at android.app.Activity.performCreate(Activity.java:8129)
W/System.err( 6008): 	at android.app.Activity.performCreate(Activity.java:8109)
W/System.err( 6008): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
W/System.err( 6008): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3749)
W/System.err( 6008): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3942)
W/System.err( 6008): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:109)
W/System.err( 6008): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/System.err( 6008): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
W/System.err( 6008): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
W/System.err( 6008): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err( 6008): 	at android.os.Looper.loopOnce(Looper.java:233)
W/System.err( 6008): 	at android.os.Looper.loop(Looper.java:344)
W/System.err( 6008): 	at `android.app.ActivityThread.main(ActivityThread.java:8212)`
W/System.err( 6008): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 6008): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
W/System.err( 6008): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
I/flutter ( 6008): error.....Some error occured while initializing UI of Payment Gateway Activity.......null
I/flutter ( 6008): code....0
I/flutter ( 6008): stacktrace....null
D/PGSDK   ( 6008): Service Stopped.
```

**Comment by Prakash128-lab** [comment]
@Yash20298 , Team are look after this issue . You can drop a mail at integration.dev@paytm.com with the request details.

**Comment by Prakash128-lab** [comment]
The issue has been fixed with new flutter release version:- paytm_allinonesdk 1.1.8

**Comment by Prakash128-lab** [comment]
> Getting Issue Some error occured while initializing UI of Payment Gateway Activity

Please check  with the new flutter release version:- paytm_allinonesdk 1.1.8
